// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXKX_A31utzehbfzyDS5-UEy0JQMUI7Hg',
    appId: '1:625277351368:web:81eef59d08866f5c537cfd',
    messagingSenderId: '625277351368',
    projectId: 'quizapp-45ff7',
    authDomain: 'quizapp-45ff7.firebaseapp.com',
    storageBucket: 'quizapp-45ff7.appspot.com',
    measurementId: 'G-LTWKDTFF8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1xesZavf3Jkw0g-bfDF378yQX1eHt8Y',
    appId: '1:625277351368:android:56cc28d209aa0f8e537cfd',
    messagingSenderId: '625277351368',
    projectId: 'quizapp-45ff7',
    storageBucket: 'quizapp-45ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmIZmnte4nd5yKUXa3vRxdxi47xna5Ozo',
    appId: '1:625277351368:ios:822e23109840b7b7537cfd',
    messagingSenderId: '625277351368',
    projectId: 'quizapp-45ff7',
    storageBucket: 'quizapp-45ff7.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXKX_A31utzehbfzyDS5-UEy0JQMUI7Hg',
    appId: '1:625277351368:web:42bae1d2800fc2d2537cfd',
    messagingSenderId: '625277351368',
    projectId: 'quizapp-45ff7',
    authDomain: 'quizapp-45ff7.firebaseapp.com',
    storageBucket: 'quizapp-45ff7.appspot.com',
    measurementId: 'G-YH51CPFPNX',
  );
}
